### PR TITLE
add demo arranger files

### PR DESCRIPTION
**Pull request by b-f-chan**
Reduced the default # of columns seen in the DMS UI results table (was too long before)

Please review if these are reasonable defaults to include as demo metadata files in the DMS installation documentation

### CODE REVIEW

**Comment by rosibaj** [comment]
@b-f-chan im not sure how to review this in this form; i don't see any changes.  What am i looking for?

**Comment by b-f-chan** [comment]
At @rosibaj, my mistake, correct this does not show deltas/changes and is very difficult to interpret.

It will be easier if you can review the facets and columns displayed on Overture QA which contain the reduced config:
https://dms-ui.staging.overture.bio/

Also see attached Excel file comparing the original to the reduced default:
[Default Arranger Fields v2.xlsx](https://github.com/overture-stack/dms/files/6190779/Default.Arranger.Fields.v2.xlsx)

**Comment by rosibaj** [comment]
lgtm!

**Review by rosibaj — APPROVED** [review]

**Comment by b-f-chan** [comment]
Thanks for the quick review @rosibaj !

**Review by caravinci — APPROVED** [review]
LGTM :shipit:

**Comment by b-f-chan** [comment]
Thanks @caravinci !  Merging !

**Pull request merged**
